import React from 'react';
import { FileText, Download, Eye, ChevronRight, Clock } from 'lucide-react';
import DataTable from '../../components/DataTable';
import Badge from '../../components/Badge';
import { usePagination } from '../../hooks/usePagination';
import { paperService } from '../../api/paperService';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import type { Paper } from '../../types';

const SchoolPapersPage: React.FC = () => {
    const navigate = useNavigate();
    const {
        data,
        loading,
        setSearch,
        page,
        setPage,
        limit,
        setLimit,
        pagination,
        refresh,
    } = usePagination<Paper>({
        url: 'http://localhost:3000/papers',
        initialLimit: 10,
    });

    const handleDownload = async (id: string) => {
        try {
            toast.info('Downloading paper...');
            await paperService.downloadPaper(id);
            toast.success('Download started');
        } catch (error) {
            toast.error('Download failed');
        }
    };

    const columns = [
        {
            header: 'Exam Paper Details',
            accessor: (p: any) => (
                <div className="flex items-center gap-4 py-1">
                    <div className="w-12 h-12 rounded-2xl bg-brand-blue/10 text-brand-blue flex items-center justify-center shrink-0">
                        <FileText className="w-6 h-6" />
                    </div>
                    <div className="flex flex-col gap-1">
                        <span className="text-[15px] font-black text-gray-900 group-hover:text-brand-blue transition-colors leading-tight font-gujarati">{p.title}</span>
                        <div className="flex items-center gap-3">
                            <div className="flex items-center gap-1 text-[10px] font-black text-gray-400 uppercase tracking-widest bg-gray-50 px-2 py-0.5 rounded">
                                {p.standard?.name || 'N/A'}
                            </div>
                            <div className="flex items-center gap-1 text-[10px] font-black text-gray-400 uppercase tracking-widest bg-gray-50 px-2 py-0.5 rounded">
                                {p.subject?.name || 'N/A'}
                            </div>
                        </div>
                    </div>
                </div>
            )
        },
        {
            header: 'Generated By',
            accessor: (p: any) => (
                <div className="flex items-center gap-2 text-sm font-bold text-gray-600">
                    <div className="w-6 h-6 rounded-full bg-gray-200 flex items-center justify-center text-[10px] font-black text-gray-500 uppercase">
                        {p.teacher?.name?.[0] || 'T'}
                    </div>
                    {p.teacher?.name || 'Unknown'}
                </div>
            )
        },
        {
            header: 'Logistics',
            accessor: (p: Paper) => (
                <div className="flex flex-col gap-1">
                    <div className="flex items-center gap-2">
                        <span className="text-sm font-black text-gray-800">{p.totalMarks} Marks</span>
                    </div>
                    <div className="flex items-center gap-2 text-[10px] font-black text-gray-400 uppercase tracking-widest">
                        <Clock className="w-3 h-3" />
                        {new Date(p.createdAt).toLocaleDateString()}
                    </div>
                </div>
            )
        },
        {
            header: 'Visibility',
            accessor: () => (
                <Badge variant="success">
                    Published
                </Badge>
            )
        },
        {
            header: 'Actions',
            accessor: (p: Paper) => (
                <div className="flex items-center gap-2">
                    <button
                        onClick={() => navigate(`/school/papers/${p.id}`)}
                        className="p-2.5 rounded-xl border border-gray-100 text-gray-400 hover:text-brand-blue hover:bg-brand-blue/5 transition-all shadow-sm"
                        title="View Paper"
                    >
                        <Eye className="w-4 h-4" />
                    </button>
                    <button
                        onClick={() => handleDownload(p.id)}
                        className="p-2.5 rounded-xl border border-gray-100 text-gray-400 hover:text-brand-blue hover:bg-brand-blue/5 transition-all shadow-sm"
                        title="Download PDF"
                    >
                        <Download className="w-4 h-4" />
                    </button>
                </div>
            ),
            className: "text-right"
        }
    ];

    return (
        <div className="space-y-10 animate-in fade-in slide-in-from-bottom-6 duration-1000">
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
                <div className="space-y-2">
                    <h1 className="text-4xl font-black text-gray-900 tracking-tight leading-tight uppercase italic underline decoration-brand-blue/30 decoration-8 underline-offset-8">Institutional Repository</h1>
                    <p className="text-gray-500 font-bold uppercase tracking-[0.2em] text-[10px] flex items-center gap-2">
                        Exam Records <ChevronRight className="w-3 h-3" /> <span className="text-brand-blue">All Validated Papers</span>
                    </p>
                </div>

                <div className="flex gap-4">
                    <div className="relative group overflow-hidden bg-gray-100/50 border border-gray-200 p-1 rounded-2xl flex">
                        <button className="px-8 py-3 bg-white text-gray-900 rounded-xl text-xs font-black uppercase tracking-widest shadow-lg shadow-gray-200/50 transition-all">Archival</button>
                        <button className="px-8 py-3 bg-transparent text-gray-400 rounded-xl text-xs font-black uppercase tracking-widest hover:text-gray-900 transition-all">Templates</button>
                    </div>
                </div>
            </div>

            <DataTable
                columns={columns}
                data={data}
                isLoading={loading}
                onSearch={setSearch}
                onRefresh={refresh}
                pagination={pagination ? {
                    currentPage: page,
                    totalPages: pagination.totalPages,
                    onPageChange: setPage,
                    pageSize: limit,
                    onPageSizeChange: setLimit,
                    totalRecords: pagination.totalRecords,
                } : undefined}
            />
        </div>
    );
};

export default SchoolPapersPage;
